---
site_name: Asset Management
site_description: Asset Management System
site_author: Connect IT
repo_name: asp
repo_url: https://gitlab.com/m4riok/asp
dev_addr: 127.0.0.1:9000

theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: blue grey
      accent: teal
  logo: img/asp.png
  favicon: img/asp.png
  features:
    - content.code.annotate
    - navigation.instant

markdown_extensions:
  - tables
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mkdocstrings:
  - search
  - minify:
      minify_html: true

nav:
  - index.md

