---
site_name: Strawberry Django Extras
site_description: Extra functionality build on top of Strawberry Django
site_author: Giorgos Gernas
repo_name: strawberry-django-extras
repo_url: https://github.com/m4riok/strawberry-django-extras
dev_addr: 127.0.0.1:9000

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: blue grey
    accent: teal
  logo: img/sdj-extras.png
  favicon: img/sdj-extras.png
  features:
    - content.code.annotate
    - navigation.instant

markdown_extensions:
  - tables
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mkdocstrings:
  - search
  - minify:
      minify_html: true

nav:
  - index.md
  - quickstart.md
  - Guide:
    - guide/jwt.md
    - guide/validation.md
    - guide/permissions.md
    - guide/hooks.md
    - guide/mutations.md
    - guide/pagination.md
  - community-projects.md


